#!usr/env/python
#Modeling a bank for practice //Kyle Atkins\\

from random import randint # random wont import....?!?!?

class Bank(object):
    def __init__(self, name):
        self.name = name

#   Should Account be a method of bank since all banks have accounts?
class Account(object):
    def __init__(self, balance, name, account_number):
        self.balance = balance
        self.name = name
        self.account_number = account_number

#   How can I deposit / withdraw to & from specific accounts?
    def deposit(self, amount):
        if amount > self.balance:
            print "Deposited $%s" % amount
            self.balance = amount + self.balance
            return self.balance
            

#   How can I deposit / withdraw to & from specific accounts?
    def withdraw(self, amount):
        if amount - self.balance < 0:
            print "Withdrew $%s" % amount
            self.balance = self.balance - amount
            return self.balance - amount
        else:
            print "Insufficient funds!"


#should have default accounts associated with User()
class User(object):
    def __init__(self, name):
        self.name = name

#Testing, is there a better way to test programs? importing to console?


bank = Bank('TC Bank')

my_account = Account(0, 'My account', 505)

user_kyle = User('Kyle')


print my_account.name
print user_kyle.name

my_account.deposit(500)
print my_account.balance
my_account.withdraw(250)
print my_account.balance
